### ISSUE TITLE
Cell Type: New Plugin

### ISSUE THREAD

**Issue by neomorphic** [connectome-neuprint/neuPrintExplorerPlugins#41]
At a high level, the point of the plugin is to try to show the inputs and outputs for a given cell type.  The challenge is that a cell type often have several example neurons in the dataset … each neuron will have both biological and reconstruction variations and potentially cropping issues (since the volume is more complete on the right than left).
As a result, I have implemented some code that tries to find common inputs and outputs between neurons.  The  user will be given a ‘canonical neuron’ that will represent the most typical neuron.
The interface will be something like this
/api/npexplorer/celltype?dataset=blah&type=blah2
neuprint http will then send a lot of JSON data back that then should be made into a cell type ‘playing card’.  I will provide more information on this format when I finish the interface.
The plugin or playing card should have the following (the information will be in the json unless otherwise noted):
• Show the cell type name, the number of neurons that make up that cell type
• Show the body id and instance name for the most centroid neuron
• provide a drop down list of neuron body ids (instances in parentheses) for all neurons in the class … highlight the ‘good’ neurons (these are ones that are not cropped or otherwise incomplete) — the default selected neuron should be the centroid
• show the sunburst chart for the selected neuron (will require a query to get sunburst info)
• show the skeleton for the selected neuron (will require a query to get the skeleton)
• show the strongest inputs and outputs highlighting the inputs or outputs that are not canonical (I provide this in the file) — maybe show just the largest X and have a “show more” button
• show the biggest inputs and outputs that other neurons have that this selected neuron is missing
• show a table that shows all the neurons and their inputs and outputs in the table … highlight entries that are a large percentage from the median value (the table might need to be cropped to fit the screen)
• if there are >=4 neurons, show a 2D cluster plot for each neuron
• show the distance matrix for the neurons with the distance score

**Comment by stephenplaza** [comment]
Small feature request for this plugin: allow user copy all neuron ids for a cell type into the user's copy buffer

**Comment by neomorphic** [comment]
@stephenplaza, couldn't that be a huge number of ids? Or are you limiting the number of ids shown on the page?

**Comment by stephenplaza** [comment]
Most cell types have fewer than few dozen neurons of a given type (or will when we finish classifying them).  The worst-case might be a few hundred.

For the most part, the visuals for the cell type plugin will be specific to a neuron (like the sunburst, skeleton view, and input/output tables).  The list of all neurons will be in the drop-down selector.  This feature request is just to populate a buffer to paste in some other tool (like neutu).

I suspect that the visualization that shows the input and output feature table for all neurons will be too big for a single page.  It probably make sense to only show the biggest neuron ids (including the selected neuron) and the biggest features.

**Comment by stephenplaza** [comment]
I don't think you need to show the list of all body ids except for the body id drop-down, the scatterplot with body IDs visible on hover over, and whatever fits in the input / output feature table.

**Comment by neomorphic** [comment]
API to use for page:

https://emdata1.int.janelia.org:13000/api/npexplorer/celltype/hemibrain/FB04oj

**Comment by stephenplaza** [comment]
Small UI suggestions:

We should indicate in the drop down list which neuron is the "centroid".  We should also highlight the current selected neuron in the common input/output table and sort the table so that the 'good' neurons are separated from the less complete ones (and indicate the difference in the graph).

The "median" row should just show the value.  The colors will highlight the differences from the median.
