### ISSUE TITLE
add better description/labels on sunburst plot

### ISSUE THREAD

**Issue by stephenplaza** [connectome-neuprint/neuPrintExplorerPlugins#48]
To make interpreting the sunburst plot easier, consider the following

* Instead of #outputs, maybe #downstream connections
* Add a note on the bottom that says connections are filtered to be between traced neurons

**Comment by neomorphic** [comment]
@stephenplaza downstream connections may be too large a string for the sunburst. Would "downstream" work? If we are changing this value, should we also change "inputs"?

For the filtered note, are both inputs and outputs filtered? Do we need to specify that in the comment?

**Comment by stephenplaza** [comment]
#downstream #upstream is probably fine.

As far as I can tell, you are filtering both up and down to be traced neurons.  I think saying connections are filtered to traced neurons is sufficient to cover up and down.

**Comment by neomorphic** [comment]
@stephenplaza, shall I replace all occurrences of inputs and outputs on the cell type of the day page as well? https://neuprint.janelia.org/results?dataset=hemibrain%3Av1.0.1&qt=findneurons&qr%5B0%5D%5Bcode%5D=ct&qr%5B0%5D%5Bds%5D=hemibrain%3Av1.0.1&qr%5B0%5D%5Bpm%5D%5Bdataset%5D=hemibrain%3Av1.0.1&qr%5B0%5D%5Bpm%5D%5BcellType%5D=PDL15u_b_pct&tab=0

**Comment by neomorphic** [comment]
Fixed in c8bde08ffccef0d967d38614e0b13f2a131b6a1a and released
